services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
  backend:
    container_name: backend
    build: 
      context: ./backend
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: always
