services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - 8000:5000
    restart: always
